[build.environment]
  NODE_VERSION = "18.19.0"  # 锁定具体版本，与package.json保持一致
  NPM_VERSION = "10.2.3"    # 锁定npm版本
  NEXT_TELEMETRY_DISABLED = "1"  # 禁用Next.js遥测，加速构建

[build]
  command = "npm ci && npm run build"
  publish = ".next"

# 防止构建超时
[build.processing]
  skip_processing = false
