[build]
  command = "npm run build:sitemap"
  publish = "dist"

# 重定向规则
[[redirects]]
  from = "https://www.iplmanufacturer.com/*"
  to = "https://iplmanufacturer.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.iplmanufacturer.com/*"
  to = "https://www.iplmanufacturer.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://iplmanufacturer.com/*"
  to = "https://iplmanufacturer.com/:splat"
  status = 301
  force = true

# SPA 回退
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 安全和SEO头部
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    X-Robots-Tag = "index, follow"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Sitemap头部
[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=86400"